name: Virash
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2
environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_calendar_carousel: ^2.4.0
  toggle_switch: ^2.0.1
  passwordfield: ^0.1.0
  connectivity_plus: ^2.3.6
  font_awesome_flutter: ^9.0.0
  flutter_rating_bar: ^4.0.0
  intl: ^0.17.0
  animations: ^2.0.0
  analog_clock: ^0.1.0
  dio: ^4.0.6
  fluttertoast: ^8.0.8
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  cross_file_image: ^0.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.11
  get: ^4.6.5
  google_maps_flutter: ^2.1.10
  table_calendar: ^3.0.3
  flutter_spinkit: ^5.1.0
  animated_splash_screen: ^1.1.0
  introduction_screen: ^2.1.0
  sms_autofill: ^2.1.2
  curved_navigation_bar: ^1.0.1
  google_fonts: ^2.2.0
  firebase_core: ^1.10.6
  firebase_crashlytics: ^2.4.4
  firebase_messaging: ^11.2.4
  flutter_windowmanager: ^0.2.0
  expandable: ^5.0.1
  syncfusion_flutter_pdfviewer: ^19.4.41-beta
  random_string: ^2.3.1
  cached_network_image: ^3.2.0
  webview_flutter: ^3.0.0
  video_player: ^2.2.11
  chewie: ^1.2.2
  youtube_player_flutter: ^8.0.0
  youtube_player_iframe: ^2.2.2
  flutter_launcher_icons: ^0.9.2
  package_info_plus: ^1.3.0
  date_format: ^2.0.7
  flutter_neat_and_clean_calendar: ^0.3.8+22
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/virash.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/fitness_app/
      - assets/
      - assets/images/
      - assets/no_data.png
      - asset/images/
      - asset/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400